// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Grill_Arrange_Test.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GrillMenuItemModel
    {
        /// <summary>
        /// Initializes a new instance of the GrillMenuItemModel class.
        /// </summary>
        public GrillMenuItemModel() { }

        /// <summary>
        /// Initializes a new instance of the GrillMenuItemModel class.
        /// </summary>
        public GrillMenuItemModel(Guid? id = default(Guid?), string name = default(string), int? length = default(int?), int? width = default(int?), string duration = default(string), int? quantity = default(int?))
        {
            Id = id;
            Name = name;
            Length = length;
            Width = width;
            Duration = duration;
            Quantity = quantity;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Length")]
        public int? Length { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Width")]
        public int? Width { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Duration")]
        public string Duration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Quantity")]
        public int? Quantity { get; set; }

    }
}
