// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Grill_Arrange_Test.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Menu representation
    /// </summary>
    public partial class GrillMenuModel
    {
        /// <summary>
        /// Initializes a new instance of the GrillMenuModel class.
        /// </summary>
        public GrillMenuModel() { }

        /// <summary>
        /// Initializes a new instance of the GrillMenuModel class.
        /// </summary>
        public GrillMenuModel(Guid? id = default(Guid?), string menu = default(string), IList<GrillMenuItemModel> items = default(IList<GrillMenuItemModel>))
        {
            Id = id;
            Menu = menu;
            Items = items;
        }

        /// <summary>
        /// Menu ID
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// Menu Name
        /// </summary>
        [JsonProperty(PropertyName = "menu")]
        public string Menu { get; set; }

        /// <summary>
        /// Menu items list
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<GrillMenuItemModel> Items { get; set; }

    }
}
